language: generic

sudo: required
services: 
  - docker

before_install:
  - docker build -t bayoudock/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bayoudock/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "ap-northeast-3"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-3-026860357374"
  bucket_path: "docker-react"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"